# Umbrella Chart for Apache Kafka + UI
# Bundles Kafka and Kafka-UI together
apiVersion: v2
name: kafka
description: Apache Kafka + UI deployment via GitOps
type: application
version: 1.0.0
appVersion: "3.6.0"

dependencies:
  - name: kafka
    version: 31.0.0
    repository: https://charts.bitnami.com/bitnami
  - name: kafka-ui
    version: 0.7.6
    repository: https://provectus.github.io/kafka-ui-charts
